  backend_solis:
    build: ./backend
    container_name: backend_solis
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./backend/.env:/app/.env:ro   # opcional, monta el archivo si tu app busca el archivo .env
    ports:
      - "8000:8000"
    depends_on:
      - db_carlos
    networks:
      - carlos_net

  frontend_carlos:
    build: ./frontend
    container_name: frontend_carlos
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - API_BASE=${API_BASE}
    ports:
      - "80:80"
    depends_on:
      - backend_solis
    networks:
      - carlos_net
